#!/bin/ruby

#$sub1 = "s/USB_OTG_CORE_HANDLE/HANDLE/g"
# $sub = "s/USB_OTG_CORE_//g"
#$sub2 = "s/USB_OTG_//g"
#$sub2 = "s/DCD_//g"

#sub1 = "s/USBD_OK/UU_OK/g"
#sub2 = "s/USBD_BUSY/UU_BUSY/g"
#sub3 = "s/USBD_FAIL/UU_FAIL/g"
#sub4 = "s/USBD_Status/UU_Status/g"
#sub5 = "s/USBD_//g"

sub1 = "s/STS/Status/g"
sub2 = "s/UU_Status/Status/g"
sub3 = "s/UU_FAIL/FAIL/g"
sub4 = "s/UU_OK/OK/g"
sub5 = "s/UU_BUSY/BUSY/g"

files = %w(
library/core.c
library/protos.h
library/public.c
library/types.h
library/usb_conf.h
library/usb_core.h
library/usb_std.h
driver/driver.c
driver/interrupts.c
driver/usb_dcd.c
driver/usb_dcd.h
driver/usb_defines.h
driver/usb_regs.h
vcp/cdc.c
vcp/class.c
vcp/conf.h
vcp/desc.c
vcp/vcp.c
vcp/vcp.h
)

def process ( f, sub )
  #puts f
  cmd = "sed -i -e #{sub} #{f}"
  puts cmd
  system cmd
end

files.each { |f|
#  process f, $sub1
  process f, sub1
  process f, sub2
  process f, sub3
  process f, sub4
  process f, sub5
}

# THE END
